services:
  myapplication:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - C:\Users\HOLDE\Desktop\Fundraising-Web-App:/app
    working_dir: /app
    command: python main.py
    depends_on:
      - mongodb
    networks:
      - web-network

  mongodb:
    image: mongo:8.0.0-rc13
    container_name: mongodb
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

  
