services:
  selenium-hub:
      image: selenium/hub:4.13.0-20230926
      container_name: selenium-hub
      ports: 
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
      networks:
        - web-network

  chrome:
    image: selenium/node-chrome:4.13.0-20230926
    shm_size: 6gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=16
    networks:
      - web-network

  myapplication:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    command: python main.py
    depends_on:
      - selenium-hub
      - mongodb
    networks:
      - web-network

  mongodb:
    image: mongo:8.0.0-rc13
    container_name: mongodb
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

  
